# See also: https://github.com/kubernetes-sigs/kind/blob/fd64a56b0c3d5654eb6d22bce812e2a87eac5853/images/base/files/etc/containerd/config.toml
# Devbox dual-snapshotter example:
# - runtime handler "devbox-runc"         -> snapshotter "devbox"
# - runtime handler "devbox-stargz-runc"  -> snapshotter "stargz"

# explicitly use v2 config format
version = 2

[plugins."io.containerd.grpc.v1.cri".containerd]
  default_runtime_name = "runc"
  snapshotter = "overlayfs"
  disable_snapshot_annotations = false

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.devbox-runc]
  runtime_type = "io.containerd.runc.v2"
  snapshotter = "devbox"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.devbox-stargz-runc]
  runtime_type = "io.containerd.runc.v2"
  snapshotter = "stargz"

[proxy_plugins]
  [proxy_plugins.stargz]
    type = "snapshot"
    address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"
  [proxy_plugins.stargz.exports]
    root = "/var/lib/containerd-stargz-grpc/"
